from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from datetime import datetime

def generate_pdf(data, plant_status, fish_status, alerts, file_name="aquaponics_report.pdf"):

    c = canvas.Canvas(file_name, pagesize=letter)
    width, height = letter

    y = height - 50

    # Title
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y, "Smart Aquaponics System Report")

    y -= 30
    c.setFont("Helvetica", 12)
    c.drawString(50, y, f"Date: {datetime.now()}")

    # Sensor Data
    y -= 40
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Sensor Data:")

    y -= 20
    c.setFont("Helvetica", 12)

    for key in data:
        y -= 20
        c.drawString(60, y, f"{key}: {data[key]}")

    # AI Results
    y -= 40
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "AI Analysis:")

    y -= 20
    c.setFont("Helvetica", 12)
    c.drawString(60, y, f"Plant Status: {plant_status}")
    y -= 20
    c.drawString(60, y, f"Fish Status: {fish_status}")

    # Alerts
    y -= 40
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Alerts:")

    y -= 20
    c.setFont("Helvetica", 12)

    if len(alerts) == 0:
        c.drawString(60, y, "No Alerts - System Stable")
    else:
        for a in alerts:
            y -= 20
            c.drawString(60, y, f"- {a}")

    # Footer
    y -= 50
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, y, "Generated by Smart Aquaponics AI System")

    c.save()

    return file_name